name: Evil Genius Labs
description: Purveyor of finely hand-crafted pixels. ê©œ
url: https://evilgeniuslabs.org
author: Jason Coon
permalink: /:title
markdown: kramdown
plugins:
  - jekyll-redirect-from
